repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-zero ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.6
    hooks:
      # export server requirements
      - id: uv-export
        args: [ --no-hashes, --group, server, --format, requirements-txt ]