"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# ruff: noqa
from .settings_base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-57n#00kj-+u9afysgxz6_-nl*ot+5rplg2q5()24+a(++z#mim"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "Leaderboard.db",
    }
}
