name: Build and release
# description: named container image and deploy on version tag
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run : docker build . --tag ghcr.io/tuesd4y/ankileaderboard:${{ github.ref_name }}
      - name: Push image
        run: docker push ghcr.io/tuesd4y/ankileaderboard:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/46524967884/locations/global/workloadIdentityPools/github/providers/tuesd4y-ankileaderboard'
          service_account: 'leaderboard-github-deploy@anki-leaderboard.iam.gserviceaccount.com'

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'anki-leaderboard'
          image: 'us-central1-docker.pkg.dev/anki-leaderboard/ghcr/tuesd4y/ankileaderboard:${{ github.ref_name }}'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
